//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TextReader.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TextReader.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 蛋
        ///妙蛙种子
        ///妙蛙草
        ///妙蛙花
        ///小火龙
        ///火恐龙
        ///喷火龙
        ///杰尼龟
        ///卡咪龟
        ///水箭龟
        ///绿毛虫
        ///铁甲蛹
        ///巴大蝶
        ///独角虫
        ///铁壳蛹
        ///大针蜂
        ///波波
        ///比比鸟
        ///大比鸟
        ///小拉达
        ///拉达
        ///烈雀
        ///大嘴雀
        ///阿柏蛇
        ///阿柏怪
        ///皮卡丘
        ///雷丘
        ///穿山鼠
        ///穿山王
        ///尼多兰
        ///尼多娜
        ///尼多后
        ///尼多朗
        ///尼多力诺
        ///尼多王
        ///皮皮
        ///皮可西
        ///六尾
        ///九尾
        ///胖丁
        ///胖可丁
        ///超音蝠
        ///大嘴蝠
        ///走路草
        ///臭臭花
        ///霸王花
        ///派拉斯
        ///派拉斯特
        ///毛球
        ///摩鲁蛾
        ///地鼠
        ///三地鼠
        ///喵喵
        ///猫老大
        ///可达鸭
        ///哥达鸭
        ///猴怪
        ///火暴猴
        ///卡蒂狗
        ///风速狗
        ///蚊香蝌蚪
        ///蚊香君
        ///蚊香泳士
        ///凯西
        ///勇基拉
        ///胡地
        ///腕力
        ///豪力
        ///怪力
        ///喇叭芽
        ///口呆花
        ///大食花
        ///玛瑙水母
        ///毒刺水母
        ///小拳石
        ///隆隆石
        ///隆隆岩
        ///小火马
        ///烈焰马
        ///呆呆兽
        ///呆壳兽
        ///小磁怪
        ///三合一磁怪
        ///大葱鸭
        ///嘟嘟
        ///嘟嘟利
        ///小海狮
        ///白海狮
        ///臭泥
        ///臭臭泥
        ///大舌贝
        ///刺甲贝
        ///鬼斯
        ///鬼斯通
        ///耿鬼
        ///大岩蛇
        ///催眠貘
        ///引梦貘人
        ///大钳蟹
        ///巨钳蟹
        ///霹雳电球
        ///顽皮雷弹
        ///蛋蛋
        ///椰蛋树
        ///卡拉卡拉 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string monsname_chs {
            get {
                return ResourceManager.GetString("monsname_chs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 蛋
        ///妙蛙種子
        ///妙蛙草
        ///妙蛙花
        ///小火龍
        ///火恐龍
        ///噴火龍
        ///傑尼龜
        ///卡咪龜
        ///水箭龜
        ///綠毛蟲
        ///鐵甲蛹
        ///巴大蝶
        ///獨角蟲
        ///鐵殼蛹
        ///大針蜂
        ///波波
        ///比比鳥
        ///大比鳥
        ///小拉達
        ///拉達
        ///烈雀
        ///大嘴雀
        ///阿柏蛇
        ///阿柏怪
        ///皮卡丘
        ///雷丘
        ///穿山鼠
        ///穿山王
        ///尼多蘭
        ///尼多娜
        ///尼多后
        ///尼多朗
        ///尼多力諾
        ///尼多王
        ///皮皮
        ///皮可西
        ///六尾
        ///九尾
        ///胖丁
        ///胖可丁
        ///超音蝠
        ///大嘴蝠
        ///走路草
        ///臭臭花
        ///霸王花
        ///派拉斯
        ///派拉斯特
        ///毛球
        ///摩魯蛾
        ///地鼠
        ///三地鼠
        ///喵喵
        ///貓老大
        ///可達鴨
        ///哥達鴨
        ///猴怪
        ///火爆猴
        ///卡蒂狗
        ///風速狗
        ///蚊香蝌蚪
        ///蚊香君
        ///蚊香泳士
        ///凱西
        ///勇基拉
        ///胡地
        ///腕力
        ///豪力
        ///怪力
        ///喇叭芽
        ///口呆花
        ///大食花
        ///瑪瑙水母
        ///毒刺水母
        ///小拳石
        ///隆隆石
        ///隆隆岩
        ///小火馬
        ///烈焰馬
        ///呆呆獸
        ///呆殼獸
        ///小磁怪
        ///三合一磁怪
        ///大蔥鴨
        ///嘟嘟
        ///嘟嘟利
        ///小海獅
        ///白海獅
        ///臭泥
        ///臭臭泥
        ///大舌貝
        ///刺甲貝
        ///鬼斯
        ///鬼斯通
        ///耿鬼
        ///大岩蛇
        ///催眠貘
        ///引夢貘人
        ///大鉗蟹
        ///巨鉗蟹
        ///霹靂電球
        ///頑皮雷彈
        ///蛋蛋
        ///椰蛋樹
        ///卡拉卡拉 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string monsname_cht {
            get {
                return ResourceManager.GetString("monsname_cht", resourceCulture);
            }
        }
    }
}
